import Head from 'next/head'
import { useEffect, useState } from 'react'
import { HOST } from 'src/store/modules/user'
import axios from 'axios'
import ItemList from 'src/components/ItemList'
import { Loader } from 'semantic-ui-react'
import 'semantic-ui-css/semantic.min.css'

export default function Home() {
  const [list, setList] = useState([])
  const [isLoading, setIsLoading] = useState(true)
  const url = `${HOST}/main`
  console.log(list.id)
  const getData = async () => {
    const res = await axios.get(url)
    // console.log(res.data)
    setList(res.data.content)
    setIsLoading(false)
  }
  useEffect(() => {
    getData()
  }, [])
  return (
    <>
      {isLoading && (
        <div>
          <Head>
            <title>케이해커 - 개발자 해외취업 커뮤니티</title>
          </Head>
          <Loader inline="centered" active>
            Loading
          </Loader>
        </div>
      )}
      {!isLoading && (
        <div>
          <Head>
            <title>케이해커 - 개발자 해외취업 커뮤니티</title>
          </Head>
          <ItemList list={list} />
        </div>
      )}
    </>
    // <div className={styles.container}>
    //   <Head>
    //     <title>Create Next App</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>

    //   <main className={styles.main}>
    //     <h1 className={styles.title}>
    //       Welcome to <a href="https://nextjs.org">Next.js!</a>
    //     </h1>

    //     <p className={styles.description}>
    //       Get started by editing <code className={styles.code}>pages/index.js</code>
    //     </p>

    //     <div className={styles.grid}>
    //       <a href="https://nextjs.org/docs" className={styles.card}>
    //         <h2>Documentation &rarr;</h2>
    //         <p>Find in-depth information about Next.js features and API.</p>
    //       </a>

    //       <a href="https://nextjs.org/learn" className={styles.card}>
    //         <h2>Learn &rarr;</h2>
    //         <p>Learn about Next.js in an interactive course with quizzes!</p>
    //       </a>

    //       <a href="https://github.com/vercel/next.js/tree/canary/examples" className={styles.card}>
    //         <h2>Examples &rarr;</h2>
    //         <p>Discover and deploy boilerplate example Next.js projects.</p>
    //       </a>

    //       <a href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app" className={styles.card}>
    //         <h2>Deploy &rarr;</h2>
    //         <p>Instantly deploy your Next.js site to a public URL with Vercel.</p>
    //       </a>
    //     </div>
    //   </main>

    //   <footer className={styles.footer}>
    //     <a
    //       href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //       target="_blank"
    //       rel="noopener noreferrer"
    //     >
    //       Powered by{' '}
    //       <span className={styles.logo}>
    //         <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
    //       </span>
    //     </a>
    //   </footer>
    // </div>
  )
}
